# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laurent Yen-Pon - Portfolio
email: lyenpon974@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/www.lyenpon.fr" # the subpath of your site, e.g. /blog
url: "https://laurent974.github.io" # the base hostname & protocol for your site
github_username:  cow974

# Build settings
markdown: kramdown

exclude: ["_app",
          "Gemfile",
          "css",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

keep_files: [assets]
permalink: pretty
